python  test.py --trgt shapenet --model_file model_m2s.ptdgcnn --gpu 2
python  test.py --trgt shapenet --model_file model_m2s.ptdgcnn --gpu 2
python  test.py --trgt shapenet --model_file model_m2s.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_m2r.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_m2r.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_m2r.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_s2m.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_s2m.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_s2m.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_s2r.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_s2r.ptdgcnn --gpu 2
python  test.py --trgt scannet --model_file model_s2r.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_r2m.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_r2m.ptdgcnn --gpu 2
python  test.py --trgt modelnet --model_file model_r2m.ptdgcnn --gpu 2
python  test.py --trgt shapenet --model_file model_r2s.ptdgcnn --gpu 2
python  test.py --trgt shapenet --model_file model_r2s.ptdgcnn --gpu 2
python  test.py --trgt shapenet --model_file model_r2s.ptdgcnn --gpu 2